### ISSUE TITLE
Link check in Hub no longer accessible: 500 Internal Server Error

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#436]
I wanted to check to see if any AASHE.org links are bad to identify any missing files. It appears the entire [link checking section in Admin](https://hub.aashe.org/_ad/linkcheck/) is down.

**Comment by baronvonvaderham** [comment]
The root cause of this: `ValueError: The file 'admin/js/jquery.min.js' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fc15abf1190>.
`

This is actually the same issue we had run into previously but it was my understanding that this was fixed. I have no idea why it suddenly stopped working in production (it still works fine in staging). I've upgraded to version 1.4, but no change.

I'll have to leave this one to @rerb who actually has more experience with that bug that I do.

**Comment by unbracketed** [comment]
I haven't been able to replicate this my local environment yet.  I have some ideas related to research around the error message and the `whitenoise` package in use to help with the static file serving.

@monika-aashe I need staff access to the Hub site so I can load that page on production and poke around more (we were waiting on sync from Membersuite earlier for my new account `brian@lincolnloop.com`)

**Comment by monika-aashe** [comment]
I just granted you super-user status, Brian. Let me know if you can access it now. https://hub.aashe.org/_ad/

**Comment by unbracketed** [comment]
Thank you @monika-aashe. I'm logged in with my account on the hub site, but when I go to the admin I see:

![screenshot 2017-07-21 09 09 56](https://user-images.githubusercontent.com/17127/28472189-7229b9a0-6df4-11e7-8ee6-27fb9db184a2.png)

Here is what I look like in Membersuite:

![screenshot 2017-07-21 09 11 08](https://user-images.githubusercontent.com/17127/28472222-9327c444-6df4-11e7-9d77-c0d65e4f87fd.png)

**Comment by monika-aashe** [comment]
Okay, I made a tweak to the access level. I assumed that granting Superuser status would be sufficient initially, but I also just granted Staff Status, which says it will give you access to the Admin specifically. Hopefully that will address the issue? 

![screen shot 2017-07-21 at 12 14 59 pm](https://user-images.githubusercontent.com/15214797/28472391-66510718-6e0e-11e7-8571-142398bf5f4a.png)

**Comment by unbracketed** [comment]
That worked, thank you.

I have occasionally seen situations where a superuser needed the staff flag for accessing things. That seems like a bug - like you assumed, a superuser should be able to do anything.

**Comment by monika-aashe** [comment]
Good to hear!

As an aside... 
In the event that you are able to make progress on this ticket, there are two lower-priority issues related to the Link Check feature that may be worth looking at (in the event it's more efficient to tackle them simultaneously):

https://github.com/AASHE/hub/issues/423
https://github.com/AASHE/hub/issues/424

**Comment by monika-aashe** [comment]
@unbracketed , let me know if you can duplicate the Internal Server Error.

**Comment by unbracketed** [comment]
I was hopeful I had a solution but when I deployed to the production hub site, it went into a bad state so I rolled back. 

The problem I addressed was that the linkcheck package implicitly needs a Django admin copy of jQuery, but the path it references is out-of-date, so the file is never found by collectstatic.  I added a copy of jQuery to our own `static` dir at the correct location which in theory would fix the problem (and did in local testing). Now I'm seeing a new error, will need to research a little more:

```
2017-07-26T22:14:57.583812+00:00 heroku[router]: at=info method=GET path="/_ad/linkcheck/" host=hub.aashe.org request_id=59fafdf3-0df0-4ae7-ba45-bcca1f260768 fwd="47.145.249.150
" dyno=web.1 connect=1ms service=13145ms status=500 bytes=244 protocol=https
2017-07-26T22:14:57.535872+00:00 app[web.1]: 07/26/2017-22:14:56:ERROR:django.request:Internal Server Error: /_ad/linkcheck/
2017-07-26T22:14:57.535883+00:00 app[web.1]: Traceback (most recent call last):
2017-07-26T22:14:57.535884+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
2017-07-26T22:14:57.535885+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2017-07-26T22:14:57.535886+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
2017-07-26T22:14:57.535887+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2017-07-26T22:14:57.535887+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
2017-07-26T22:14:57.535889+00:00 app[web.1]:     if test_func(request.user):
2017-07-26T22:14:57.535889+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/views/decorators.py", line 12, in <lambda>
2017-07-26T22:14:57.535890+00:00 app[web.1]:     lambda u: u.is_active and u.is_staff,
2017-07-26T22:14:57.535891+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/functional.py", line 204, in inner
2017-07-26T22:14:57.535892+00:00 app[web.1]:     self._setup()
2017-07-26T22:14:57.535896+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/functional.py", line 351, in _setup
2017-07-26T22:14:57.535897+00:00 app[web.1]:     self._wrapped = self._setupfunc()
2017-07-26T22:14:57.535898+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 22, in <lambda>
2017-07-26T22:14:57.535898+00:00 app[web.1]:     request.user = SimpleLazyObject(lambda: get_user(request))
2017-07-26T22:14:57.535899+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 10, in get_user
2017-07-26T22:14:57.535899+00:00 app[web.1]:     request._cached_user = auth.get_user(request)
2017-07-26T22:14:57.535900+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 173, in get_user
2017-07-26T22:14:57.535901+00:00 app[web.1]:     backend = load_backend(backend_path)
2017-07-26T22:14:57.535901+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
2017-07-26T22:14:57.535902+00:00 app[web.1]:     return import_string(path)()
2017-07-26T22:14:57.535903+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
2017-07-26T22:14:57.535903+00:00 app[web.1]:     module = import_module(module_path)
2017-07-26T22:14:57.535904+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2017-07-26T22:14:57.535905+00:00 app[web.1]:     __import__(name)
2017-07-26T22:14:57.535906+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django_membersuite_auth/backends.py", line 4, in <module>
2017-07-26T22:14:57.535906+00:00 app[web.1]:     from membersuite_api_client.security.services import (
2017-07-26T22:14:57.535907+00:00 app[web.1]: ImportError: cannot import name get_user_for_membersuite_entity
```

**Comment by unbracketed** [comment]
Back in business: https://hub.aashe.org/_ad/linkcheck/

**Comment by monika-aashe** [comment]
Reopening because the link check once again is showing up as "Internal Server Error"

**Comment by unbracketed** [comment]
Link checker is fixed: https://hub.aashe.org/_ad/linkcheck/

**Comment by monika-aashe** [comment]
Looks good, closing.
