### ISSUE TITLE
"Project Size" filter under Green Power Projects is broken

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#468]
Applying this filter in any views results in "Internal Server Error.

**Comment by unbracketed** [comment]
```
2017-11-10T17:00:15.787242+00:00 app[web.1]: [2017-11-10 17:00:15 +0000] [14] [ERROR] Error handling request /browse/types/greenpowerproject/?search=&gallery_view=list$
content_type=greenpowerproject&country=&project_size=101-1000
2017-11-10T17:00:15.787244+00:00 app[web.1]: Traceback (most recent call last):
2017-11-10T17:00:15.787244+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
2017-11-10T17:00:15.787245+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2017-11-10T17:00:15.787245+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 181, in handle_request
2017-11-10T17:00:15.787246+00:00 app[web.1]:     for item in respiter:
2017-11-10T17:00:15.787247+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/api/web_transaction.py", line 738, in _
_iter__
2017-11-10T17:00:15.787247+00:00 app[web.1]:     for item in self.generator:
2017-11-10T17:00:15.787248+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/api/web_transaction.py", line 1114, in 
__call__
2017-11-10T17:00:15.787248+00:00 app[web.1]:     self.start_response)
2017-11-10T17:00:15.787250+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/api/web_transaction.py", line 1242, in 
_nr_wsgi_application_wrapper_
2017-11-10T17:00:15.787250+00:00 app[web.1]:     return wrapped(*args, **kwargs)
2017-11-10T17:00:15.787251+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
2017-11-10T17:00:15.787251+00:00 app[web.1]:     response = self.get_response(request)
2017-11-10T17:00:15.787281+00:00 app[web.1]:     return wrapped(*args, **kwargs)

...

2017-11-10T17:00:15.787282+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
2017-11-10T17:00:15.787282+00:00 app[web.1]:     result = block.nodelist.render(context)
2017-11-10T17:00:15.787282+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 992, in render
2017-11-10T17:00:15.787283+00:00 app[web.1]:     bit = node.render_annotated(context)
2017-11-10T17:00:15.787283+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
2017-11-10T17:00:15.787283+00:00 app[web.1]:     return self.render(context)
2017-11-10T17:00:15.787284+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
2017-11-10T17:00:15.787284+00:00 app[web.1]:     return nodelist.render(context)
2017-11-10T17:00:15.787285+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 992, in render
2017-11-10T17:00:15.787285+00:00 app[web.1]:     bit = node.render_annotated(context)
2017-11-10T17:00:15.787285+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
2017-11-10T17:00:15.787286+00:00 app[web.1]:     return self.render(context)
2017-11-10T17:00:15.787286+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/templatetags/cache.py", line 28, in render
2017-11-10T17:00:15.787287+00:00 app[web.1]:     raise TemplateSyntaxError('"cache" tag got a non-integer timeout value: %r' % expire_time)
2017-11-10T17:00:15.787287+00:00 app[web.1]: TemplateSyntaxError: "cache" tag got a non-integer timeout value: ''
```

**Comment by unbracketed** [comment]
I worked on this a few different times on Friday but am not yet sure of the root cause.  Part of the problem is that I cannot replicate the error in my development environment, despite trying to simulate the same caching setup. The error seems to happen whenever the `project_size` filter adds to the result set.

**Comment by unbracketed** [comment]
Fixed. Here is an example search with the `10 - 100 kW` filter applied: https://hub.aashe.org/browse/types/greenpowerproject/?search=&gallery_view=list&content_type=greenpowerproject&country=&project_size=10to100#resources-panel

**Comment by monika-aashe** [comment]
Looks good, closing.
